### ISSUE TITLE
callbacks and Mongoid compatibility

### ISSUE THREAD

**Issue by wyattisimo** [GetStream/stream-rails#10]
I'm curious as to why you're using `after_commit` instead of `after_create` and `after_destroy` here: https://github.com/GetStream/stream-rails/blob/master/lib/stream_rails/sync_policies.rb.

Using `after_commit` will cause data discrepancies if the call to the Stream API fails because it does not roll back the DB transaction.

Using `after_create` and `after_destroy` would not only allow ActiveRecord to roll back the transactions to keep the local data consistent with what's in Stream, but it would also make the callbacks compatible with Mongoid (Mongoid doesn't use `after_commit` because it has no transactions).

**Comment by tbarbugli** [comment]
```after_create``` and ```after_destroy``` are executed within the same transaction of the record save/delete.

1. If the API call to Stream fails (eg. something wrong in the integration code, a networking issue client-side, ...) the transaction rolls-back and the record is not created or destroyed. This is really bad for apps that use Stream for not critical purposes or that can live with few missing activities.
2. If an insert transaction rolls back after the activity is created, we end up with broken references in feeds (in pretty much every app deletes are orders of magnitude less common than inserts).

Using ```after_commit``` or ```after_create``` (and the delete counter-part) is a trade off, they both come with pros and cons. ```after_commit``` seems to raise less issues.

Perhaps adding a sync policy class that use ```after_create``` would make it easier for mongoid users. I would be very happy to add Mongoid support for this gem, how far did you get with that? Any PR is very very welcome!

**Comment by wyattisimo** [comment]
I think something as simple as #16 would do it. Thoughts?

**Comment by tbarbugli** [comment]
looks good! going to give it a test and see if it's good to merge, thank you! how is the integration going for you? did you have to change many other things to get mongoid work?

**Comment by tbarbugli** [comment]
@wyattisimo everything looks good to me. before merging I would really like to know how your integration went and if you needed other changes other than the one you put in #16 
Thanks!
