### ISSUE TITLE
Missing Auth Header

### ISSUE THREAD

**Issue by MuhammadRazaAslam** [GetStream/stream-rails#112]
I'm trying to fetch all feeds but I'm getting the following error in response.

**Request:**
`StreamRails.feed_manager.get_user_feed(current_user.id).get`
**Response:**
`{"detail":"Missing auth header.","status_code":403,"code":17,"exception":"NotAllowedException","duration":"0.00ms","more_info":"https://getstream.io/docs/api_error_responses"}
`

Anyone can tell me what's the issue?

**Comment by ferhatelmas** [comment]
This is user setup related. Replied on support ticket, not related to SDK, closing.
