### ISSUE TITLE
Enricher possible to use my model method instead of the model attributes?

### ISSUE THREAD

**Issue by joshuairl** [GetStream/stream-rails#12]
My models have a "serialize" method that returns a basic object containing exactly the formatted data I want to be sent to the clients from my api.

I tried changing my model to be like this:
```
def activity_actor
    follower.user.serialize
  end

  def activity_object
    followable.user.serialize
  end
```

But it's still sending the entire user model...?

**Comment by tbarbugli** [comment]
are you those users AR model instances?

**Comment by joshuairl** [comment]
They should be, yep.

**Comment by joshuairl** [comment]
I'm sorry, should look like this:
```
  def activity_actor
    self.follower.serialize
  end

  def activity_object
    self.followable.serialize
  end
```

**Comment by joshuairl** [comment]
But yes, they are instances of "User" model.
And the User model has a serialize method to create an object presentable to the clients.

**Comment by joshuairl** [comment]
In console if I do:
`follow = Follow.find(27)`

Then I do:
`follow.followable.serialize`

I get the expected serialized result.

**Comment by tbarbugli** [comment]
the gem integrates nicely with AR models, just return them and you will get serialization/deserialization for free.

eg.

```ruby
 def activity_actor
    self.follower
  end
```

**Comment by joshuairl** [comment]
Yes, but my clients require a specific response from the API.

**Comment by joshuairl** [comment]
In console if I do `follow.activity_actor` it returns the serialized version.
But `activities = enricher.enrich_aggregated_activities(results)`
is returning full model serialized instead of my custom version of it.

**Comment by joshuairl** [comment]
The issue is that the gem seems to just return all of the model properties and I'm just wanting a customized subset of them.
For instance, avatarUrl which is a method of user is in the serialized object returned from serialize method.

**Comment by tbarbugli** [comment]
AR model instances are stored in activities as string references (eg. "user:42"), when activities are enriched the references are replaced with the right model instances (as they were loaded with User.find(42)).

**Comment by tbarbugli** [comment]
so unless I miss the point, one simple solution is to loop over the activities and replace actor field with actor.serialize (where activities is the result of ```enricher.enrich_aggregated_activities(results)```)

**Comment by joshuairl** [comment]
That did it!
Thanks
