### ISSUE TITLE
Error when saving comment

### ISSUE THREAD

**Issue by joshuairl** [GetStream/stream-rails#13]
I'm using acts_as_commentable.

My comment model looks like this:
```
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :user
  belongs_to :commentable, :polymorphic => true
  include StreamRails::Activity
  as_activity
  default_scope -> { order('created_at ASC') }

  def activity_notify
    if self.commentable_type == 'Archive'
      [
        StreamRails.feed_manager.get_notification_feed(self.commentable.host_id),
        StreamRails.feed_manager.get_notification_feed(self.commentable.peer_id)
      ]
    end
  end

  def activity_object
    self.commentable
  end
end
```

For some reason, everytime I save I'm getting error:
`user_id can only contain alphanumeric characters plus underscores and dashes`

**Comment by tbarbugli** [comment]
could you print the values for host_id,peer_id and user_id?

**Comment by joshuairl** [comment]
Figured it out, thanks! 
For some reason the plugin wasn't allowing me to do comment.user = @current_user.
I changed it up a bit and it's working good now.

**Comment by therise3107** [comment]
hey there i am facing the same problem, my logic is same as well im doing @task.owner = current_user
but this is working fine with my comment model
