### ISSUE TITLE
Does activity_notify ONLY send to those feeds? or is it in addition to other feeds?

### ISSUE THREAD

**Issue by joshuairl** [GetStream/stream-rails#14]
Does it put it in other feeds as well as the ones I specify there or is it isolating this to ONLY go in those feeds I specify in activity_notify?

**Comment by tbarbugli** [comment]
activity_notify specifies a list of feeds that will get a copy of the activity (similar to email' CC field)

**Comment by joshuairl** [comment]
How does that differ from `stream-ruby`'s `:to => []`?

**Comment by tbarbugli** [comment]
`activity_notify` is used to generate the `to` field for the activity
