### ISSUE TITLE
How would I represent this activity...

### ISSUE THREAD

**Issue by joshuairl** [GetStream/stream-rails#15]
John Smith commented on Susy Smith's post entitled "Things I love".
          "I love your things I love list!" <--- this would be john's comment

So I would need:
- Actor (John Smith)
- Owner (Susy Smith)
- Post (title: "Things I love")
- Comment (message: "I love your things I love list!") 

Right?  Maybe this is out of the scope of `stream-rails`?
Maybe question for `stream-ruby`?

**Comment by joshuairl** [comment]
Would the #activity_object be the `comment` or the `post` in this situation?
I'd hate to pass along "extra_info" when I could simply grab it from my DB during the "enrichment" process?

Would the activity stream spec `target` property be used in this situation at all?

**Comment by tbarbugli** [comment]
I would use the `comment` object and then access the post via AR
