### ISSUE TITLE
Create activities manually?

### ISSUE THREAD

**Issue by toobulkeh** [GetStream/stream-rails#17]
Is there a way to use this gem if the verb/activity isn't a separate model? We have a state machine and state attribute on a model that defines "activities".

**Comment by tschellenbach** [comment]
Yes but the documentation is a bit poor. @tbarbugli where's this documented?

**Comment by tbarbugli** [comment]
you can extend the standard behavior (verb is derived from the class name) by implementing `activity_verb` in your model.

```ruby
def activity_verb
  if self.reply_to.nil?
      "post"
  else
      "retweet"
  end
end
```

**Comment by toobulkeh** [comment]
Ideally, we'd like to create activities manually:
```ruby
model.add_activity({actor: current_user, verb: "one of a hundred things", object: self})
```
But it seems like if we fall back to stream-ruby then all the enrich functionality is lost.

I'll give this a shot to see if I can come up with a solution in our concerns.

**Comment by tbarbugli** [comment]
enrichment will keep working with manually created activities as long as you use `StreamRails.create_reference` to create the AR references

**Comment by toobulkeh** [comment]
I don't think this will work, because the model is the object we're tracking, not the activity that's being performed.

For example, we have a Task model that has 3 different types of users (roles) attached to it. We have no way of determining who the owner is unless we specifically set it based on an action (not just CRUD activity).

Maybe we can create a separate Activity model that tracks the as_activity?

**Comment by toobulkeh** [comment]
We ended up creating a general Activity object with a verb for any action we want to manually create.


```
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :item, polymorphic: true
  belongs_to :target, class_name: "User"

  validates :item, :user, :verb, presence: true

  include StreamRails::Activity
  as_activity

  def activity_object
    self.item
  end

  def activity_actor
    self.user
  end

  def activity_verb
    self.verb
  end

  def activity_notify
    [StreamRails.feed_manager.get_notification_feed(self.target_id)] if target.present?
  end
end
```
