### ISSUE TITLE
Conditional Follow?

### ISSUE THREAD

**Issue by toobulkeh** [GetStream/stream-rails#18]
We have a slightly different feed system, where a single feed is represented as a specific object (imagine a forum thread) and users can follow that thread for all activity on it.

We want users to receive activities into their notification feeds, but do not want them to receive activities that they created themselves (where actor == self)

Is there a way to conditionally follow in this manner, or do we have to do the filtering on our end? I feel like it would work, but returning activities could take multiple calls.

**Comment by toobulkeh** [comment]
By the last line, I mean the problem we face if we do the filtering on our end is that if we say .get_notifications(limit: 15) and the past 15 notifications contain 3 of their own actions, we would only get 12 notifications, so we would then need to wrap everything in

**Comment by toobulkeh** [comment]
@tbarbugli any ideas for how to do this? We're getting into more complex scenarios with the TO/follow method and would prefer to build this properly instead of what feels like a hack.

Thanks!

**Comment by kennym** [comment]
@toobulkeh that is now possible with this code: https://github.com/GetStream/stream-rails/pull/28

**Comment by iandouglas** [comment]
@toobulkeh Sorry this hasn't been answered until now. Take a look at our discard rules, maybe this is what you're looking for: https://getstream.io/docs/#discard-rules
