### ISSUE TITLE
Activity Actor System?

### ISSUE THREAD

**Issue by toobulkeh** [GetStream/stream-rails#21]
We have some actions that are performed by the system or global. It appears that this implementation requires a user/actor. Is there a clean way around this that Stream will accept?

**Comment by kennym** [comment]
Same question here.

We basically want to create a feed item which appears in all feeds, e.g. a broadcast or system message.

**Comment by tbarbugli** [comment]
what about having one global feed and "cc" all activities to it?

**Comment by kennym** [comment]
> what about having one global feed and "cc" all activities to it?

Thanks - that's something we can work with.
