### ISSUE TITLE
Sequel ORM compatibility

### ISSUE THREAD

**Issue by kennym** [GetStream/stream-rails#23]
This project seems to be compatible with ActiveRecord only at first glance, but we're on a Rails project which uses Sequel as the ORM. Bummer.

What are the plans for adding Sequel support? Pull requests welcome?

**Comment by tbarbugli** [comment]
we don't have plans to add support for sequel to the library. PR are more than welcome, I can surely give you some help and suggestion if you want to add sequel support. The way this gem is structured, should make the integration with sequel fairly simple.

**Comment by kennym** [comment]
#25
