### ISSUE TITLE
Testing framework integrations?

### ISSUE THREAD

**Issue by kennym** [GetStream/stream-rails#35]
Are there any plans on integrations for testing frameworks like RSpec? Pull requests welcome?

**Comment by tbarbugli** [comment]
we have no plans yet. what is your suggestion?

**Comment by kennym** [comment]
@tbarbugli the goal would be to test activity creation with any given Ruby test framework. I am planning on tackling RSpec first, because that's what I use most and probably other developers, too.

The API, based on what I test most:

# Check that their activities in a feed
expect(StreamRails.feed_manager.get_feed()).to have_activities_count(3)
# 
expect(StreamRails.feed_manager.get_feed()).to have_activities(verb: "follow", count: 3)

This would make actual HTTP requests to GetStream and we can encourage them to use VCR (https://duckduckgo.com/?q=vcr+ruby) to reduce the load on the API and speed up their test suites.

**Comment by tbarbugli** [comment]
Perhaps what makes more sense is to use stubbing to make sure that requests are properly created by the client and VCR to make sure responses can be decoded/read properly.
