### ISSUE TITLE
How to use StreamRails.config.news_feeds with custom feed names?

### ISSUE THREAD

**Issue by kennym** [GetStream/stream-rails#37]
I have the following slugs for my feeds:
* `timeline_flat` (instead of `flat`)
* `timeline_aggregated` (instead of `aggregated`)

set like this:

```
StreamRails.configure do |config|
  config.news_feeds = { flat: "timeline_flat", aggregated: "timeline_aggregated" }
end
```

However, upon trying to call the news feed like this:

```
StreamRails.feed_manager.get_news_feeds(current_user.id)[:flat]
```

I get an error. Also with this:

```
StreamRails.feed_manager.get_news_feeds(current_user.id)[:timeline_flat]
```

Any ideas what I might be doing wrong?

**Comment by kennym** [comment]
@tbarbugli @tschellenbach

**Comment by kennym** [comment]
The culprit seems to be this line: https://github.com/GetStream/stream-rails/blob/master/lib/stream_rails/feed_manager.rb#L18

The custom news_feed name is never passed along to your API. I wonder if that's supposed to happen, or if I am just misunderstanding the API.

If I try to change the logic to use the custom news_feed names provided by the initializer, as follows:

```
# This
Hash[@news_feeds.map { |k, _v| [_v, get_feed(_v, user_id)] }]
# Instead of this...
Hash[@news_feeds.map { |k, _v| [k, get_feed(k, user_id)] }]
```

I get the following error: 

```*** Stream::StreamInputData Exception: feed_slug can only contain alphanumeric characters```

Do you really not allow alphanumeric characters for feed slugs?

**Comment by tschellenbach** [comment]
That definitely sounds like a bug. Can you try making the API call from stream-ruby instead of stream-rails? @tbarbugli what do you think?

**Comment by kennym** [comment]
@tschellenbach that definitely worked for me:

```
STREAM_CLIENT.feed("timeline_flat", "4").get()
=> {"duration"=>"59ms",
"results"=>[ OMMITTED] }
```

Yes, that works. So, this is definitely a bug.

**Comment by kennym** [comment]
You need to merge https://github.com/GetStream/stream-ruby/pull/46 before merging this to get it to work. :+1: Hope this helps.
