### ISSUE TITLE
Site-wide Stream Activity

### ISSUE THREAD

**Issue by ACPK** [GetStream/stream-rails#48]
How would I have a specific model's stream show up for all users?

**Comment by ACPK** [comment]
I'd also like an admin's stream to show all activity.

**Comment by desmondhume** [comment]
I actually just made all existing users follow those ubiquitous feeds and add an `after_create` callback in order to make new users automatically follow said feeds.

I don't know if it's the standard way to do it (i don't even know if there's one), but it should work just fine 👯

**Comment by iandouglas** [comment]
@ACPK @desmondhume Generally we recommend making a global flat feed and copying activities to that, and having all users also follow that feed, if those things are important for everyone to see.
