### ISSUE TITLE
Displaying grouped[:aggregated] feeds

### ISSUE THREAD

**Issue by gauravtiwari** [GetStream/stream-rails#5]
Hello @tbarbugli 

I have configured activity feeds and it's all working except the display of Aggregated feeds. 

How to display aggregated feeds so that it displays like - 

*You followed Tom, Jessica and 2 more people*
*You followed Tom and Jessica*

Do I have to alter the partials to respond if a feed is flat or aggregated? 

Thanks,
Gaurav

**Comment by tbarbugli** [comment]
I added a simple example to the example app. https://github.com/GetStream/Stream-Example-Ruby/blob/f08d55ae8126c45b66efb5a66a462e63d2bf2bfa/app/views/aggregated_activity/_pin.html.erb
