### ISSUE TITLE
Upgrade to latest version of stream-ruby? 

### ISSUE THREAD

**Issue by asmatameem** [GetStream/stream-rails#51]
stream-rails is using a much older version of stream-ruby where the ` Stream::Client ` doesn't expose methods like ` update_activity ` and ` update_activities `. Any plans of upgrading it?

**Comment by tbarbugli** [comment]
good point, updating to last version of the client is very safe (no breaking changes were introduced). We are going to do this very soon!

**Comment by iandouglas** [comment]
Hi @asmatameem , I'll take a look at this and let you know what I find.

**Comment by iandouglas** [comment]
@asmatameem can you contact me at ian@getstream.io when you have a minute to chat? I have a few questions for you.

**Comment by iandouglas** [comment]
All done!
