### ISSUE TITLE
Notification feed needs configuring? 

### ISSUE THREAD

**Issue by JeffreyCheng92** [GetStream/stream-rails#53]
I've followed the basic instructions in my rails application and am current stuck on this line of code.

```
def activity_notify
    [StreamRails.feed_manager.get_notification_feed(self.parent.user.id)]
end
```

It seems everytime I try to push an event into the target's notification feed, I get the error: 
`FeedConfigException details: The following feeds are not configured: 'user'`

I have the following configuration inside the initializer:

```
config.news_feeds = { 
   flat: 'timeline_flat', 
   aggregated: 'timeline_aggregated'
}
config.notification_feed = 'Notification'
```

On the dashboard, I've created a notification feed called: 
![image](https://cloud.githubusercontent.com/assets/12540391/18531894/8ac231dc-7a8d-11e6-9ec0-cd56236a62d4.png)

I'm not sure why I need to configure/create a user feed when that has nothing to do with my notification feed. Or maybe I need to create a new notification feed called "user"? If so, then what was the point of setting this configuration: `config.notification_feed = 'Notification'` and what does it do? Thanks for your help.

**Comment by iandouglas** [comment]
@JeffreyCheng92 I'm still fairly new to Stream, but I'm happy to dig into this if you're still having a problem. That the code is trying to fetch that user's notification feed, but I believe the user model uses a flat feed called 'user' for user activities. Like I said, I'm happy to dig into it more if you still need assistance; let me know.

**Comment by JeffreyCheng92** [comment]
@iandouglas Sorry I didn't get back to you sooner but I'm still having issues. 

Here's some extra information to go off of.

```
feed = StreamRails.feed_manager.get_notification_feed(16468)                  
=> #<Stream::Feed:0x007fa5a87d8520
 @client=
  #<Stream::Client:0x007fa5a8be4330
 ...
 @feed_name="notification16468", # HERE THE NAME OF THE FEED IS 'notification'
 @feed_url="notification/16468", # HERE THE NAME OF THE FEED IS 'notification'
 @id="notification:16468", # HERE THE NAME OF THE FEED IS 'notification'
 @slug="notification", # HERE THE NAME OF THE FEED IS 'notification'
 @user_id=16468>

feed.get 
=> Stream::StreamApiResponseException: FeedConfigException details: The following feeds are not configured: 'notification'
```

Compared to here where I explicitly state the name: 

```
feed = StreamRails.client.feed('Notification', 16468)
=> #<Stream::Feed:0x007fa5a8b32d88
 @client=
  #<Stream::Client:0x007fa5a74a96e8
 ....
 @feed_name="Notification16468", # HERE ITS CAPITALIZED AND NAMED 'Notification'
 @feed_url="Notification/16468",
 @id="Notification:16468",
 @slug="Notification",
 @user_id=16468>

feed.get 
=> {"duration"=>"23ms",
 "next"=>"",
 "results"=>
  [{"activities"=>
     [{"actor"=>"User:12144",
       "foreign_id"=>"Praise:571",
       "id"=>"xzxzxzxzxzxzxzx",
       "object"=>"Review:480295",
       "origin"=>nil,
       "target"=>nil,
       "time"=>"2016-10-31T21:46:13.000000",
       "to"=>["Notification:16468"],
       "verb"=>"Praise"}],
    "activity_count"=>1,
    "actor_count"=>1,
    "created_at"=>"2016-10-31T21:46:13.000000",
    "group"=>"None27710305",
    "id"=>"zxzxzxzxzxzx",
    "is_read"=>false,
    "is_seen"=>false,
    "updated_at"=>"2016-10-31T21:46:13.000000",
    "verb"=>"Praise"}],
 "unread"=>1,
 "unseen"=>1}
```

The name of the feed in the online dashboard is `Notification` (notice the capital N). You can see in the former that without explicitly stating the name of the feed, it returns lower case `notifications`, which doesn't match the configuration in my `StreamRails` initializer at all.

**Comment by iandouglas** [comment]
Can you check your app on your dashboard and see whether your notification feed is called "Notification" or "notification" (first character is uppercase or not) ?

**Comment by JeffreyCheng92** [comment]
On my online dashboard:

![image](https://cloud.githubusercontent.com/assets/12540391/19874677/3aa19262-9f84-11e6-9e88-e06eb4af1597.png)

and within my StreamRails configuration:

```
StreamRails.configure do |config|
  config.api_key     = Rails.application.secrets[:stream_key]
  config.api_secret  = Rails.application.secrets[:stream_secret]
  config.timeout     = 30                # Optional, defaults to 3
  config.location    = 'us-east'         # Optional, defaults to 'us-east'
  # If you use custom feed names, e.g.: timeline_flat, timeline_aggregated,
  # use this, otherwise omit:
  config.news_feeds = { 
    flat: 'timeline_flat', 
    aggregated: 'timeline_aggregated',

  }
  # Point to the notifications feed group providing the name, 
  # omit if you don't have a notifications feed
  config.notification_feed = 'Notification'
end
```

Yet `StreamRails.feed_manager.get_notification_feed(16468)` returns a feed with name `@feed_name="notification16468"`. See lowercase `n` instead of capital `N`.

**Comment by mikeyduece** [comment]
@JeffreyCheng92 I had the same problem. I changed `flat: 'timeline_flat` to `flat: 'timeline` and it worked for me.
