### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by l4u** [GetStream/stream-rails#55]
is rails 5 supported?

**Comment by tbarbugli** [comment]
@iandouglas did you check?

**Comment by iandouglas** [comment]
@l4u I'm looking into this. I'm curious if this is a problem with our lower-level stream-ruby library than a Rails issue, but here's where it's failing: https://travis-ci.org/GetStream/stream-rails/jobs/186844368

**Comment by ACPK** [comment]
Any update?

**Comment by iandouglas** [comment]
@ACPK No update at this time. Is this something you'd be willing to help with by contributing some code?

**Comment by ACPK** [comment]
@iandouglas - Absolutely if we move forward with Stream. Would you be available this week for a call? My email is ak@callred.com.

**Comment by jkeam** [comment]
Just curious on the progress of this?

**Comment by jkeam** [comment]
I've been using v2.5.2 bc newest is problematic for me.

Newest gives me this error:
`NoMethodError: undefined method `split' for nil:NilClass`

**Comment by tbarbugli** [comment]
We added Rails 5 support a while back and updated the example app to use it (https://github.com/GetStream/Stream-Example-Rails). @jkeam can you share more about the issue that you are experiencing?

**Comment by ruggi** [comment]
@jkeam there were indeed some issues in the library, they should be fixed now (for both Rails 5.0 and 5.2), with the version 2.6.1 of the gem. Could you let me know if it works fine on your side now?

**Comment by ruggi** [comment]
Closing this issue.

**Comment by jkeam** [comment]
I hate to comment on a closed issue but wanted to drop a note just incase someone else ran into what I ran into.

Looks like the default news_feeds changed (https://github.com/GetStream/stream-rails/commit/00b8db607a30cdcbdb89bbbf898825d324c8ad2e), so just had to add:

```
config.news_feeds = { flat: 'flat', aggregated: 'aggregated' }
```

and I'm all good again  :)
