### ISSUE TITLE
feed_name and naming issue in general

### ISSUE THREAD

**Issue by krtschmr** [GetStream/stream-rails#60]
automatically it becomes `class.downcase`

```
 @feed_name="user1",
 @feed_url="user/1",
 @id="user:1",
```

why is this and why don't we keep the rails convention of namespacing `Admin::User` or `User::Image` ?

i found out that the stream is case-sensitive so we can run into lots of problems here

i think it's a better approach to make it

```
 @feed_name="User1",
 @feed_url="User/1",
 @id="User:1",
```

or then

```
 @feed_name="AdminUser1",
 @feed_url="AdminUser/1",
 @id="Admin::User:1",
```

```

def timeline_object(obj)
 "#{obj.class}:#{obj.id}"
end

```

you write in your docs at some point
` The left half of the string:string metadata value when split on : must also match the name of the model.`

but the truth is, the model isnt called `user`, indeed its name is `User`. As rails follows Convention over Configuration we should follow this route and change this behaviour pretty fast, as this gem is still in an early stage

thoughts?

**Comment by tbarbugli** [comment]
Is enrichment not working in your case? If yes, can you provide the model and some more information about the error?

**Comment by krtschmr** [comment]
actually the whole gem is not working since i have huge `method_missing` for gem-models (`acts_as_follower` as an example) so i populate the stuff myself with basic ruby code




```
  def publish!
    create_activity_stream
    super
  end

  private
    def create_activity_stream
      unless $stream_disabled
        feeds = [timeline_object(owner), timeline_object(self)]
        data = { actor: timeline_object(owner), verb: 'created_mod', object: timeline_object(self) } #, target: to_object(Mod::Image.last) }
        $stream.add_to_many(data, feeds)
      end
    end
```

this is when i detected that the user feed 
https://github.com/GetStream/stream-rails/blob/master/lib/stream_rails/feed_manager.rb#L14
somehow uses `user:1` and for that reason won't work with our heavy namespaced models.

**Comment by tbarbugli** [comment]
is there a specific reason you did not use the built-in integration approach for your models?

```
class MyModelActivity < ActiveRecord::Base
  include StreamRails::Activity
  as_activity

  def activity_owner_feed
    'user'
  end

  def activity_owner_id
    self.user.id
  end

  def activity_actor
    self.user
  end

  def activity_object
    self.item
  end

  def activity_notify
    'notification:X'
  end

```

**Comment by krtschmr** [comment]
yes, the reason is *control*. i do see the benefit of using the magic of the gem for small applications. we currently have about 35 models that somehow interact with each other. when i tried the rails-gem somehow the magic was too much ;)

**Comment by krtschmr** [comment]
Actually, the initial problem is still unsolved. We should have an eye on the naming-convention
