### ISSUE TITLE
Removing Fields from Enriched Data

### ISSUE THREAD

**Issue by tobeee** [GetStream/stream-rails#65]
Hi guys,

Just wondering if anyone has found an easy way to strip fields out from the Actor property to remove sensitive information (like email etc)

Ideally would prefer to whitelist available properties - anyone had any luck?

Thanks!

**Comment by iandouglas** [comment]
Hi @tobeee ... when the enrichment runs you'll get the full user object available for your view to process, but it's really up to your code to restrict access to things, not Stream. If you're passing the data to a front-end system and serializing it as JSON first you can certainly tweak your serializer to remove certain fields from the output. Again, that's out of scope for our library, though.
