### ISSUE TITLE
Issue with feed enrichment

### ISSUE THREAD

**Issue by adambedford** [GetStream/stream-rails#67]
I'm running into an issue with feed enrichment, whereby it doesn't actually enrich the activity feed.

The result I'm getting from the API is this:

```
[{"activities"=>
   [{"actor"=>"User:3",
     "foreign_id"=>"Events::Applied:44",
     "id"=>"3ed3ae00-d148-11e7-8080-80004c5f321a",
     "object"=>"Events::Applied:44",
     "origin"=>nil,
     "target"=>"",
     "time"=>"2017-11-24T18:49:48.000000",
     "verb"=>"Events::Applied"}],
  "activity_count"=>1,
  "actor_count"=>1,
  "created_at"=>"2017-11-24T18:49:48.839288",
  "group"=>"Events::Applied_2017-11-24",
  "id"=>"3f53beb9-d148-11e7-8080-80012cf2ee2d",
  "is_read"=>false,
  "is_seen"=>false,
  "updated_at"=>"2017-11-24T18:49:48.839288",
  "verb"=>"Events::Applied"}]
```

This is an array of hashes with each hash containing the key `activities` and  `StreamRails::Enrich#collect_references` accepts this array, however it loops through each hash in the array looking for the keys `[:actor, :object, :target]`, which aren't in the top-level hash but instead nested under the `activities` key. This results in nothing being enriched.

Did the API change at all? It seems like `collect_references` should take each hash and loop through `activity["activities"]` instead.

**Comment by iandouglas** [comment]
This looks like an aggregated feed type? I'll look into it.

**Comment by iandouglas** [comment]
Er, apologies, the seen/read flags are in notification feed groups, not aggregated feeds. I'm not aware of anything changing lately to cause this, but I'll check into it.

**Comment by adambedford** [comment]
It is a notification feed and it just seems like the json structure doesn't align with what the enricher is expecting

**Comment by iandouglas** [comment]
Gave a workaround via email that loops through the activities grouped up in the notification feed. It appears that our SDK libraries that communicate directly with an ORM only enrich flat feeds and aggregated feeds, so I'm going to flag this as "won't fix" for the time being. When we get enough customers asking for notification feed enrichment, we'll revisit this.
