### ISSUE TITLE
undefined method `enriched?' for #<Hash:0x000000069cebf8>

### ISSUE THREAD

**Issue by yo-gen** [GetStream/stream-rails#74]
I have following code in my controller and views respectively. The feed is returned correctly in the controller. But template rendering throws this error.
undefined method `enriched?' for #<Hash:0x000000069cebf8>
Anyone has any idea?

```
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
  	@enricher = StreamRails::Enrich.new
	@feed = StreamRails.feed_manager.get_notification_feed(current_user.id)
	@results = @feed.get()['results']
	@activities = @enricher.enrich_activities(@results)
  end

end
```

Following is the view code

```
<div class="container">
    <div class="container-pins">
    	<% byebug %>
      <% for activity in @activities %>
          <%= render_activity activity %>
      <% end %>
    </div>
</div>
```

**Comment by rromanchuk** [comment]
Getting the same error for activity that is an aggregation 

```ruby
enricher = StreamRails::Enrich.new
feed = StreamRails.feed_manager.get_news_feeds(user_id)[:timeline_aggregated]
results = feed.get()['results']
@activities = enricher.enrich_activities(results)
```


<img width="563" alt="screen shot 2018-04-23 at 12 59 31 pm" src="https://user-images.githubusercontent.com/102188/39150142-329b8e90-46f6-11e8-96cb-63b0b46b76f4.png">

**Comment by rromanchuk** [comment]
Also looks like `enricher.enrich_activities(results)` does nothing for aggregated feeds

**Comment by yo-gen** [comment]
Documented the change and made a pull request.

https://github.com/GetStream/stream-rails/pull/77

**Comment by rromanchuk** [comment]
Yeah we both did the same thing lol https://github.com/GetStream/stream-rails/pull/76
