### ISSUE TITLE
Best practice for updated_at, created_at timestamp strings?

### ISSUE THREAD

**Issue by rromanchuk** [GetStream/stream-rails#79]
I'm noticing my client side date formatter is failing because my timestamps aren't being rendered the same way rails is formatting my active record `created_at`, `updated_at` columns. Since i'm getting these back as strings from  the `getstream` enricher, should i run them through some normalization process like `Time.parse("2018-05-09T03:32:41.997959").iso8601`? 

```
{"created_at"=>"2018-05-09T00:54:06.123351", 
"updated_at"=>"2018-05-09T05:40:06.526624"}
```

The format string on the client i'm using is: 
```swift
public init() {
        
  let formatter = DateFormatter()
  formatter.locale = Locale(identifier: "en_US_POSIX")
  formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
        
  super.init(dateFormatter: formatter)
}
```
I'll do some investigation, probably a user error, i don't know what is what anymore.

**Comment by rromanchuk** [comment]
Reviewing my responses: 

Rails dates being rendered:  
`"created_at": "2018-03-26T21:44:23.551Z",`

getstream date strings 
```
"created_at": "2018-05-09T00:54:06.123351",
"updated_at": "2018-05-09T05:40:06.526624",
```

**Comment by teenkung** [comment]
Rails dates being rendered:
"created_at": "2018-03-26T21:44:23.551Z",

getstream date strings

"created_at": "2018-05-09T00:54:06.123351",
"updated_at": "2018-05-09T05:40:06.526624",

**Comment by teenkung** [comment]
ผมต้องทำไงครับ
ถึงจะทำไห้เสร็จสมบูรณ์I need to do it.
It will be completed.

**Comment by dwightgunning** [comment]
Thanks for the note. I've passed this on to a Stream team member with Ruby/RoR experience as I'm unfortunately not all that familiar.

Perhaps of help is that the [stream-rails-example](https://github.com/GetStream/Stream-Example-Rails) project does have an [example](https://github.com/GetStream/Stream-Example-Rails/blob/b25bd10d36238e96f2490c29384f5c668f6fec01/app/views/items/_item.html.erb#L18) of the `created_at` timestamp being rendered.

**Comment by ruggi** [comment]
@rromanchuk as you already highlighted, there's a difference between the rails representation of dates and the one returned by API calls: for example, the Rails client sends dates (an activity's `"time"` field) to the API in the ISO 8601 format ([here](https://github.com/GetStream/stream-rails/blob/68582936c92730b3401b918bd4907f30e81a427a/lib/stream_rails/activity.rb#L80)), but the dates returned by the API are in the strict RFC3339 format (with sub-second precision).
My suggestion is indeed to normalize the dates to the format which is most suitable for your app(s) when you get them back from the enricher.

**Comment by dwightgunning** [comment]
Thanks for posing the question @rromanchuk and I hope the advice from @ruggi is helpful. I'll close this out for now but feel free to comment further or contact us with any follow ups.

**Comment by rromanchuk** [comment]
Opps, forgot to close. Thanks!

**Comment by rromanchuk** [comment]
This is more of a generic architecture question beyond the scope of getstream but I feel like you guys may hold strong opinions, or point me in the right direction. I basically rewrote my notifications so the firehose is now my "driver" for delivery and i'd like to start developing a much smarter delivery system, and by smarter, i mean coalescing common high velocity events while avoiding re-architecting what getstream has already done for me with my grouping templates. 

I have yet to come up with something elegant, but i could be overthinking it. 

https://stackoverflow.com/questions/50167098/possible-to-use-notification-firehose-for-aggregated-coalesced-apn-delivery
