### ISSUE TITLE
Verb is always name of model

### ISSUE THREAD

**Issue by palkerecsenyi** [GetStream/stream-rails#85]
For some reason, my integration of Stream is using the name of my model (`Picture`) as the verb of all its activities instead of something like 'create' - I'm not sure why.

`models/picture.rb` (excerpt):

```ruby
include StreamRails::Activity
as_activity

def activity_object
  self
end
```

The issue may be to do with my use of `self` rather than `self.item` - however, using `self.item` it throws the following error while running the `picture#create` action:

```
undefined method `item' for #<Picture:0x0000000005b1a8a0>
```

Not sure why this is happening, but thanks in advance for your help.

**Comment by palkerecsenyi** [comment]
### Update:
This snippet from `stream_rails/activity.rb` suggests that this is normal behaviour:
```ruby
def activity_verb
  self.class.model_name.to_s
end
```

If so, why is this the case?

**Comment by tbarbugli** [comment]
@palkerecsenyi this is default behavior; it works pretty well in many cases (Post, Like, Comment, ...) but you can change that easily by implementing `#activity_notify` for your Picture model.

**Comment by palkerecsenyi** [comment]
Thanks, it just wasn't making sense for `Article` 'John Smith articled Hello world'
