### ISSUE TITLE
Can you guys verify your gemspec works with stream-ruby

### ISSUE THREAD

**Issue by rromanchuk** [GetStream/stream-rails#91]
```
Bundler could not find compatible versions for gem "stream-ruby":
  In Gemfile:
    stream-ruby

    stream_rails was resolved to 2.6.5, which depends on
      stream-ruby (~> 2.6, >= 2.6.1)
```

**Comment by mircea-cosbuc** [comment]
Hi @rromanchuk. Can you please provide more details about your setup?
Spinning up an empty project with the `Gemfile`:
```
source "https://rubygems.org"

gem 'stream_rails'
```
and running
```
bundle install
```
resolves `stream-rails` to `2.6.5` and `stream-ruby` to `2.11.0`
```
...
Fetching stream-ruby 2.11.0
Installing stream-ruby 2.11.0
Fetching stream_rails 2.6.5
Installing stream_rails 2.6.5
...
```

**Comment by rromanchuk** [comment]
And stream ruby to your gem file as well

**Comment by rromanchuk** [comment]
Then bundle update

**Comment by mircea-cosbuc** [comment]
That still resolves the dependencies correctly for this basic case. The dependencies for the rails sdk haven't been updated in a while and it seems that the builds would fail with some rails versions. I'll take this opportunity to bring them up to date. Thanks for the report!

**Comment by rromanchuk** [comment]
I can make a reproducible rails project if you want. I explicitly use stream-ruby in a some places so I can't just rely on stream-rails dependency including it. I thought it was independent of rails after using `bundle outdated`.  The sanity test for the case i'm trying to use would be 

```ruby
source "https://rubygems.org"
gem "stream-ruby", "3.1.0"
gem "stream-rails"
```

I need to be able to use the latest release of the ruby client, just seems like i'm always forking to relax some dependency, or I'm drunk. 

PS this line is soon to be deprecated 
https://github.com/GetStream/stream-rails/blob/master/stream_rails.gemspec#L12

**Comment by rromanchuk** [comment]
<img width="686" alt="Screen Shot 2019-03-13 at 1 00 55 PM" src="https://user-images.githubusercontent.com/102188/54310649-1b788080-4590-11e9-99fa-78922c375564.png">

Sanity test fails
