### ISSUE TITLE
Group aggregate feeds by object instead of actor

### ISSUE THREAD

**Issue by Brotakuu** [GetStream/stream-rails#93]
Currently aggregate fields are grouped by actor (ben liked 5 photos).

I would like to  group aggregate fields by the object (24 people liked this photo)

Is this possible? My like model looks like this:

``` 	
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :photo
	include StreamRails::Activity
	as_activity

	def activity_notify
		[StreamRails.feed_manager.get_notification_feed(self.photo.user_id)]
	end

	def activity_object
		self.photo
	end

	def activity_actor
		self.user
	end

end

```

**Comment by tbarbugli** [comment]
@Brotakuu you can change how aggregation works directly from Stream's Dashboard https://getstream.io/docs/#aggregated-feeds
