### ISSUE TITLE
Update stream-ruby to the latest version (~> 4.0.0)

### ISSUE THREAD

**Issue by victorfgs** [GetStream/stream-rails#99]
Dependency stream-ruby v3.x.x is using outdated version of Faraday (< 1.0) and it's causing Gemfile conflicts with newer gems.

**Comment by victorfgs** [comment]
Just noticed that this gem is supported by ruby >= 1.9.2 and this is breaking the CI as it is now.

Is there chance to drop ruby old versions support?
stream-ruby ~> 4.0.1 requires ruby 2.5 at least

**Comment by victorfgs** [comment]
Bump [PR](https://github.com/GetStream/stream-rails/pull/100) link

**Comment by ferhatelmas** [comment]
Yes, definitely, they are too old.
